export default {
  id: 'africa',
  name: 'Afrika',
  nameEn: 'Africa',
  description: 'Afrika kıtasının ünlü şehirleri ve başkentleri',
  icon: '🌍',
  difficulty: 'hard',
  difficultyLabel: 'Zor',
  questionsPerRound: 10,
  timePerQuestion: null,
  mapBounds: [[-36.0, -20.0], [38.0, 52.0]],
  mapCenter: [2.0, 18.0],
  mapZoom: { min: 3, max: 9, start: 3 },
  dataSource: 'africa',
  scoreMultiplier: 1.3,
  unlockCondition: null,
  color: '#f59e0b',
  available: true,
};
