export default {
  id: 'europe',
  name: 'Avrupa',
  nameEn: 'Europe',
  description: 'Avrupa kıtası ve sınır topraklarından 200 şehir',
  icon: '🇪🇺',
  difficulty: 'medium',
  difficultyLabel: 'Orta',
  questionsPerRound: 10,
  timePerQuestion: null,
  mapBounds: null,
  mapCenter: [53.0, 16.0],
  mapZoom: { min: 3, max: 8, start: 4 },
  dataSource: 'europe',
  scoreMultiplier: 1.0,
  unlockCondition: null,
  color: '#3b82f6',
  available: true,
};
